"""Stage 7b — data-migration planning.

Per approved unit, produces ``workspace/datamig/<unit>/``:

- ``target_ddl_postgres.sql`` — DB2 DDL converted to PostgreSQL with a
  documented type mapping; anything without a clean mapping is flagged
  ``-- REVIEW`` rather than silently converted.
- ``proposed_schema.sql`` — VSAM/copybook -> relational proposal from the
  record layouts: OCCURS -> child tables, REDEFINES flagged for human
  decision, COMP-3 -> NUMERIC(p,s), primary key from SELECT RECORD KEY.
  A reviewable draft, never silently final.
- ``convert_<record>.py`` — runnable flat-file converters (EBCDIC cp037
  -> UTF-8, COMP-3/binary unpacking driven by the layout) each with a
  ``--self-test`` round trip (pack -> unpack -> byte-identical).
- ``datamig.md`` — the mapping doc: verdict, DB2->PG type table,
  proposal rationale, column<->field name-similarity report (reported,
  not assumed), and how to run the converters.
"""

from __future__ import annotations

import argparse
import json
import logging
import re
from pathlib import Path
from string import Template

from .config import Config
from .store import Store
from .decompose import sync_units_from_csv
from .specgen import find_unit, spec_data

log = logging.getLogger(__name__)

# DB2 -> PostgreSQL type mapping. (pattern, replacement, clean?)
_TYPE_MAP: list[tuple[str, str, bool]] = [
    (r"^DEC(?:IMAL)?\s*\((\d+)\s*,\s*(\d+)\)$", r"NUMERIC(\1,\2)", True),
    (r"^DEC(?:IMAL)?\s*\((\d+)\)$", r"NUMERIC(\1)", True),
    (r"^CHAR(?:ACTER)?\s*\((\d+)\)$", r"CHAR(\1)", True),
    (r"^VARCHAR\s*\((\d+)\)$", r"VARCHAR(\1)", True),
    (r"^TIMESTAMP$", "TIMESTAMP", True),
    (r"^DATE$", "DATE", True),
    (r"^TIME$", "TIME", True),
    (r"^SMALLINT$", "SMALLINT", True),
    (r"^INT(?:EGER)?$", "INTEGER", True),
    (r"^BIGINT$", "BIGINT", True),
    (r"^REAL$", "REAL", True),
    (r"^(?:FLOAT|DOUBLE)$", "DOUBLE PRECISION", True),
    (r"^CLOB(?:\s*\(.*\))?$", "TEXT", True),
    (r"^BLOB(?:\s*\(.*\))?$", "BYTEA", True),
    (r"^GRAPHIC\s*\((\d+)\)$", r"CHAR(\1)", False),
    (r"^VARGRAPHIC\s*\((\d+)\)$", r"VARCHAR(\1)", False),
    (r"^DECFLOAT.*$", "NUMERIC", False),
    (r"^ROWID$", "BYTEA", False),
]


def map_db2_type(db2: str) -> tuple[str, bool]:
    """(postgres type, clean-mapping?). Unknown types come back flagged."""
    t = " ".join(db2.upper().split())
    for pat, repl, clean in _TYPE_MAP:
        m = re.match(pat, t)
        if m:
            return re.sub(pat, repl, t), clean
    return t, False


def _pg_ddl(store: Store, unit_tables: set[str]) -> tuple[str, list[dict]]:
    """Regenerate PG DDL from parsed DDL facts for the unit's DDL files."""
    rows = [dict(r) | {"detail": json.loads(r["detail_json"] or "{}")}
            for r in store.query(
                "SELECT f.*, a.path FROM facts f"
                " JOIN artifacts a ON a.id=f.artifact_id"
                " WHERE f.fact_type IN ('table', 'fk', 'index')"
                " ORDER BY f.id")]
    ddl_files = {r["path"] for r in rows
                 if r["fact_type"] == "table" and r["name"] in unit_tables}
    rows = [r for r in rows if r["path"] in ddl_files]
    mapping_report: list[dict] = []
    out = ["-- PostgreSQL DDL generated by legacymod datamig from DB2 DDL",
           f"-- source file(s): {', '.join(sorted(ddl_files)) or '(none)'}",
           "-- lines marked -- REVIEW have no clean type mapping.", ""]
    for r in rows:
        if r["fact_type"] != "table":
            continue
        cols = []
        for c in r["detail"]["columns"]:
            pg, clean = map_db2_type(c["type"])
            mapping_report.append({"table": r["name"], "column": c["name"],
                                   "db2": c["type"], "pg": pg,
                                   "clean": clean})
            null = "" if c["nullable"] else " NOT NULL"
            flag = "" if clean else "   -- REVIEW: no clean mapping from DB2 "
            cols.append(f"    {c['name'].lower()} {pg}{null}{flag}")
        pk = r["detail"].get("pk") or []
        if pk:
            cols.append("    PRIMARY KEY ("
                        + ", ".join(c.lower() for c in pk) + ")")
        for fk in rows:
            if fk["fact_type"] == "fk" and fk["name"] == r["name"]:
                d = fk["detail"]
                cols.append(
                    "    FOREIGN KEY ("
                    + ", ".join(c.lower() for c in d["columns"])
                    + f") REFERENCES {d['ref_table'].lower()} ("
                    + ", ".join(c.lower() for c in d["ref_columns"]) + ")")
        out.append(f"CREATE TABLE {r['name'].lower()} (\n"
                   + ",\n".join(cols) + "\n);\n")
    for r in rows:
        if r["fact_type"] == "index":
            d = r["detail"]
            uq = "UNIQUE " if d.get("unique") else ""
            out.append(f"CREATE {uq}INDEX {r['name'].lower()} ON "
                       f"{d['table'].lower()} ("
                       + ", ".join(c.lower() for c in d["columns"]) + ");")
    return "\n".join(out) + "\n", mapping_report


def _pg_type_for_field(f: dict) -> tuple[str, str]:
    """(postgres type, note) for a copybook field."""
    pic = (f.get("pic") or "").upper()
    usage = (f.get("usage") or "DISPLAY").upper()
    if "X" in pic or "A" in pic:
        return f"VARCHAR({f['length']})", ""
    if usage in ("COMP-3", "PACKED-DECIMAL") or f.get("decimals"):
        return f"NUMERIC({f['digits']},{f['decimals']})", \
            "from COMP-3/packed" if usage.startswith(("COMP-3", "PACKED")) else ""
    if usage in ("COMP", "COMP-4", "COMP-5", "BINARY"):
        return ("BIGINT" if (f.get("digits") or 0) > 9 else "INTEGER"), \
            "from binary"
    return f"NUMERIC({f.get('digits') or 1})", ""


def _proposed_schema(data: dict, record_keys: dict[str, str]) -> str:
    out = ["-- Relational proposal from copybook/record layouts.",
           "-- Reviewable draft - REDEFINES and OCCURS decisions are yours.",
           ""]
    for rec in data["records"]:
        tname = rec["legacy_name"].lower().replace("-", "_")
        defs: list[tuple[str, str]] = []   # (sql fragment, comment)
        notes: list[str] = []
        children = []
        for f in rec["fields"]:
            cname = f["legacy_name"].lower().replace("-", "_")
            pg, note = _pg_type_for_field(f)
            comment = f"  -- {f['pic']} {f['usage']}"
            if note:
                comment += f" ({note})"
            if f.get("redefines"):
                notes.append(f"    -- REVIEW: {cname} REDEFINES "
                             f"{f['redefines'].lower()} - pick one "
                             "representation; column omitted from draft")
                continue
            if f.get("occurs"):
                children.append((cname, pg, f))
                continue
            defs.append((f"{cname} {pg}", comment))
        pk = record_keys.get(rec["legacy_name"], "")
        if pk:
            defs.append((f"PRIMARY KEY ({pk.lower().replace('-', '_')})",
                         "  -- from SELECT RECORD KEY"))
        else:
            notes.append("    -- REVIEW: no RECORD KEY found; choose a "
                         "primary key")
        cols = [f"    {sql}{',' if i < len(defs) - 1 else ''}{comment}"
                for i, (sql, comment) in enumerate(defs)]
        out.append(f"CREATE TABLE {tname} (\n"
                   + "\n".join(cols + notes) + "\n);\n")
        for cname, pg, f in children:
            out.append(
                f"-- OCCURS {f['occurs']} on {f['legacy_name']} -> child table\n"
                f"CREATE TABLE {tname}_{cname} (\n"
                f"    {tname}_id INTEGER NOT NULL,  -- FK to parent\n"
                f"    seq SMALLINT NOT NULL,        -- OCCURS index 1..{f['occurs']}\n"
                f"    {cname} {pg},\n"
                f"    PRIMARY KEY ({tname}_id, seq)\n);\n")
    return "\n".join(out)


_CONVERT_TEMPLATE = Template('''"""Flat-file converter for legacy record $record_name.

Generated by `legacymod datamig` - drives EBCDIC (cp037) and packed /
binary field handling from the copybook layout below. Run:

    python $script_name --self-test          # round-trip proof
    python $script_name in.dat out.csv       # convert a fixed-record file
"""

import argparse
import csv
import sys

LAYOUT = $layout_json

RECORD_LENGTH = $record_length


def _pack_comp3(value_str, digits, scale, signed):
    neg = value_str.strip().startswith("-")
    magnitude = value_str.strip().lstrip("+-").replace(".", "")
    magnitude = magnitude.rjust(digits, "0")[-digits:]
    if digits % 2 == 0:
        magnitude = "0" + magnitude
    sign = "d" if (neg and signed) else ("c" if signed else "f")
    return bytes.fromhex(magnitude + sign)


def _unpack_comp3(data, digits, scale, signed):
    h = data.hex()
    body, sign = h[:-1], h[-1]
    body = body[-digits:] if digits <= len(body) else body.rjust(digits, "0")
    neg = sign in ("d", "b")
    if scale:
        body = body[:-scale] + "." + body[-scale:]
    out = body.lstrip("0") or "0"
    if out.startswith("."):
        out = "0" + out
    return ("-" if neg else "") + out


def _fmt_num(value_str, scale):
    v = value_str.strip() or "0"
    if scale and "." not in v:
        v = v + "." + "0" * scale
    if scale:
        whole, frac = v.split(".")
        v = whole + "." + frac.ljust(scale, "0")[:scale]
    return v


def pack_record(values):
    buf = bytearray(b"\\x40" * RECORD_LENGTH)   # EBCDIC spaces
    for f in LAYOUT:
        raw = values.get(f["name"], "")
        if f["kind"] == "display_char":
            data = str(raw).ljust(f["length"])[: f["length"]].encode("cp037")
        elif f["kind"] == "display_num":
            digits = _fmt_num(str(raw), f["decimals"]).replace(".", "")
            digits = digits.lstrip("+-").rjust(f["digits"], "0")[-f["digits"]:]
            data = digits.encode("cp037")
        elif f["kind"] == "comp3":
            data = _pack_comp3(_fmt_num(str(raw), f["decimals"]),
                               f["digits"], f["decimals"], f["signed"])
        else:  # comp binary, big-endian signed
            iv = int(round(float(raw or 0)))
            data = iv.to_bytes(f["length"], "big", signed=True)
        buf[f["offset"]: f["offset"] + f["length"]] = data
    return bytes(buf)


def unpack_record(data):
    out = {}
    for f in LAYOUT:
        chunk = bytes(data[f["offset"]: f["offset"] + f["length"]])
        if f["kind"] == "display_char":
            out[f["name"]] = chunk.decode("cp037").rstrip()
        elif f["kind"] == "display_num":
            s = chunk.decode("cp037")
            if f["decimals"]:
                s = s[: -f["decimals"]] + "." + s[-f["decimals"]:]
            out[f["name"]] = _fmt_num(s.lstrip("0") or "0", f["decimals"])
        elif f["kind"] == "comp3":
            out[f["name"]] = _fmt_num(
                _unpack_comp3(chunk, f["digits"], f["decimals"], f["signed"]),
                f["decimals"])
        else:
            out[f["name"]] = str(int.from_bytes(chunk, "big", signed=True))
    return out


def convert_file(src, dst):
    n = 0
    with open(src, "rb") as fin, open(dst, "w", newline="",
                                      encoding="utf-8") as fout:
        writer = csv.DictWriter(fout, fieldnames=[f["name"] for f in LAYOUT])
        writer.writeheader()
        while True:
            rec = fin.read(RECORD_LENGTH)
            if len(rec) < RECORD_LENGTH:
                if rec:
                    print(f"warning: {len(rec)} trailing byte(s) ignored",
                          file=sys.stderr)
                break
            writer.writerow(unpack_record(rec))
            n += 1
    print(f"converted {n} record(s) -> {dst}")


def self_test():
    sample = $sample_json
    packed = pack_record(sample)
    values = unpack_record(packed)
    repacked = pack_record(values)
    ok = True
    for f in LAYOUT:
        a, b = sample[f["name"]], values[f["name"]]
        if str(a) != str(b):
            print(f"FIELD MISMATCH {f['name']}: packed {a!r} -> "
                  f"unpacked {b!r}")
            ok = False
    if packed != repacked:
        print("BYTE MISMATCH: pack(unpack(pack(x))) differs from pack(x)")
        ok = False
    print("ROUND-TRIP " + ("PASS: pack -> unpack -> identical fields and "
                           "identical bytes" if ok else "FAIL"))
    return 0 if ok else 1


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("src", nargs="?")
    ap.add_argument("dst", nargs="?")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()
    if args.self_test:
        sys.exit(self_test())
    if not (args.src and args.dst):
        ap.error("need src and dst (or --self-test)")
    convert_file(args.src, args.dst)


if __name__ == "__main__":
    main()
''')


def _layout(rec: dict) -> tuple[list[dict], int, dict]:
    """Converter layout + record length + sample values from a record."""
    layout = []
    cursor = 0
    sample: dict[str, str] = {}
    for i, f in enumerate(rec["fields"]):
        if f.get("redefines"):
            continue  # overlay: flagged in the proposal, skipped here
        pic = (f.get("pic") or "").upper()
        usage = (f.get("usage") or "DISPLAY").upper()
        if "X" in pic or "A" in pic:
            kind = "display_char"
            sample[f["legacy_name"]] = f"V{i}"[: f["length"]]
        elif usage in ("COMP-3", "PACKED-DECIMAL"):
            kind = "comp3"
            whole = max(f["digits"] - f["decimals"], 1)
            mag = str(10 + i)[-whole:]
            frac = ("5" + str(i))[: f["decimals"]].ljust(f["decimals"], "0")
            val = mag + ("." + frac if f["decimals"] else "")
            sample[f["legacy_name"]] = ("-" if f.get("signed") else "") + val
        elif usage in ("COMP", "COMP-4", "COMP-5", "BINARY"):
            kind = "comp"
            sample[f["legacy_name"]] = str(7 + i)
        else:
            kind = "display_num"
            whole = max(f["digits"] - f["decimals"], 1)
            val = str(2 + i)[-whole:] + \
                ("." + "25"[: f["decimals"]].ljust(f["decimals"], "0")
                 if f["decimals"] else "")
            sample[f["legacy_name"]] = val
        n = len(layout)
        layout.append({"name": f["legacy_name"], "offset": cursor,
                       "length": f["length"], "kind": kind,
                       "digits": f.get("digits", 0),
                       "decimals": f.get("decimals", 0),
                       "signed": f.get("signed", 0)})
        cursor += f["length"] * max(f.get("occurs") or 1, 1)
    return layout, cursor, sample


def _similarity_report(store: Store, data: dict,
                       unit_tables: set[str]) -> list[str]:
    lines = []
    cols = []
    for r in store.query("SELECT name, detail_json FROM facts"
                         " WHERE fact_type='table'"):
        if r["name"] in unit_tables:
            for c in json.loads(r["detail_json"] or "{}").get("columns", []):
                cols.append((r["name"], c["name"]))
    fields = [f["legacy_name"] for rec in data["records"]
              for f in rec["fields"]]
    for tbl, col in cols:
        norm_col = col.replace("_", "")
        matches = [f for f in fields if f.replace("-", "") == norm_col
                   or f.replace("-", "").endswith(norm_col)]
        if matches:
            lines.append(f"- `{tbl}.{col}` likely corresponds to copybook "
                         f"field(s) {', '.join(sorted(set(matches)))} "
                         "(name similarity - reported, not assumed)")
    return lines


def run(args: argparse.Namespace, cfg: Config) -> int:
    with Store(cfg) as store:
        sync_units_from_csv(store, cfg)
        unit = find_unit(store, args.unit)
        if not unit:
            print(f"datamig: no unit {args.unit!r}")
            return 1
        if unit["status"] == "proposed":
            print(f"datamig: unit {unit['name']} is status=proposed - "
                  "approve it in units.csv first")
            return 1
        data = spec_data(store, cfg, unit)
        out = cfg.workspace / "datamig" / unit["name"]
        out.mkdir(parents=True, exist_ok=True)

        unit_tables = set(data["tables"])
        pg_ddl, mapping = _pg_ddl(store, unit_tables)
        (out / "target_ddl_postgres.sql").write_text(pg_ddl, encoding="utf-8")

        record_keys: dict[str, str] = {}
        for r in store.query("SELECT f.detail_json FROM facts f"
                             " WHERE f.fact_type='select'"):
            d = json.loads(r["detail_json"] or "{}")
            if d.get("record_key"):
                for rec in data["records"]:
                    names = {x["legacy_name"] for x in rec["fields"]}
                    if d["record_key"] in names:
                        record_keys[rec["legacy_name"]] = d["record_key"]
        (out / "proposed_schema.sql").write_text(
            _proposed_schema(data, record_keys), encoding="utf-8")

        scripts = []
        for rec in data["records"]:
            layout, length, sample = _layout(rec)
            if not layout:
                continue
            script_name = ("convert_"
                           + rec["legacy_name"].lower().replace("-", "_")
                           + ".py")
            (out / script_name).write_text(_CONVERT_TEMPLATE.substitute(
                record_name=rec["legacy_name"], script_name=script_name,
                layout_json=json.dumps(layout, indent=1),
                record_length=length,
                sample_json=json.dumps(sample, indent=1)), encoding="utf-8")
            scripts.append(script_name)

        clean = sum(1 for m in mapping if m["clean"])
        doc = [
            f"# Data migration plan - unit {unit['name']}",
            "",
            f"**Verdict up front:** {len(mapping)} DB2 column(s) converted "
            f"({clean} clean, {len(mapping) - clean} flagged for review), "
            f"{len(data['records'])} record layout(s) proposed as tables, "
            f"{len(scripts)} conversion script(s) generated, each with an "
            "executable round-trip self-test. Nothing here is final - the "
            "proposal SQL is a reviewable draft.",
            "",
            "## DB2 -> PostgreSQL type mapping applied",
            "",
            "| table | column | DB2 type | PostgreSQL type | clean? |",
            "|---|---|---|---|---|",
        ]
        for m in mapping:
            doc.append(f"| {m['table']} | {m['column']} | {m['db2']} |"
                       f" {m['pg']} | {'yes' if m['clean'] else 'REVIEW'} |")
        doc += [
            "",
            "## Copybook -> relational proposal rationale",
            "",
            "- COMP-3 / packed decimal -> NUMERIC(p,s) with digits/scale "
            "from the PIC.",
            "- Binary (COMP) -> INTEGER/BIGINT by digit count.",
            "- OCCURS n -> a child table keyed (parent_id, seq); the draft "
            "shows the shape.",
            "- REDEFINES -> column omitted from the draft and flagged: a "
            "human must pick the canonical representation.",
            "- Primary keys come from SELECT ... RECORD KEY where present; "
            "otherwise flagged.",
            "",
            "## Column <-> field name-similarity report",
            "",
        ]
        sim = _similarity_report(store, data, unit_tables)
        doc += sim or ["- (no name-similar pairs found)"]
        doc += [
            "",
            "## Conversion scripts",
            "",
        ]
        for s in scripts:
            doc.append(f"- `{s}` - run `python {s} --self-test`, then "
                       f"`python {s} <in.dat> <out.csv>` on an EBCDIC "
                       "fixed-record extract.")
        (out / "datamig.md").write_text("\n".join(doc) + "\n",
                                        encoding="utf-8")
        print(f"datamig: {out} written (target DDL, proposal, "
              f"{len(scripts)} converter(s), mapping doc)")
        for s in scripts:
            print(f"  {s}")
    return 0
